package com.capgemini.serviciosya.beans.domain;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Adress.java
//  @ Date : 11/09/2018
//  @ Author : 
//
//




public class Address {
	private int id_address;
	private String street;
	private String number;
	private String zipCode;
	private City city;
	private Province province;
	public Address(int id_address, String street, String number, String zipCode, City city, Province province) {
		super();
		this.id_address = id_address;
		this.street = street;
		this.number = number;
		this.zipCode = zipCode;
		this.city = city;
		this.province = province;
	}
	public int getId_address() {
		return id_address;
	}
	public void setId_address(int id_address) {
		this.id_address = id_address;
	}
	public String getStreet() {
		return street;
	}
	public void setStreet(String street) {
		this.street = street;
	}
	public String getNumber() {
		return number;
	}
	public void setNumber(String number) {
		this.number = number;
	}
	public String getZipCode() {
		return zipCode;
	}
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}
	public City getCity() {
		return city;
	}
	public void setCity(City city) {
		this.city = city;
	}
	public Province getProvince() {
		return province;
	}
	public void setProvince(Province province) {
		this.province = province;
	}
}
