package com.capgemini.serviciosya.beans.domain;

import java.util.Collection;
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Consumer.java
//  @ Date : 11/09/2018
//  @ Author : 
//
//




public class Consumer extends Person {
	public Collection <Provider> seekProviders(Skill skill) {
		return null;
	
	}

	public Consumer() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Consumer(int dni, String name, String lastName, String email, String phone, Date birthDate,
			Address address) {
		super(dni, name, lastName, email, phone, birthDate, address);
		// TODO Auto-generated constructor stub
	}
}
