package com.capgemini.serviciosya.beans.domain;

import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Person.java
//  @ Date : 11/09/2018
//  @ Author : 
//
//




public abstract class Person {
	private int dni;
	private String name;
	private String lastName;
	private String email;
	private String phone;
	private Date birthDate;
	private Address address;
	
	public Person() {
		super();
	}
	public Person(int dni, String name, String lastName, String email, String phone, Date birthDate, Address address) {
		super();
		this.dni = dni;
		this.name = name;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.birthDate = birthDate;
		this.address = address;
	}
	public int getDni() {
		return dni;
	}
	public void setDni(int dni) {
		this.dni = dni;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public Date getBirthDate() {
		return birthDate;
	}
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}
	public Address getAdress() {
		return address;
	}
	public void setAdress(Address adress) {
		this.address = adress;
	}
}
