package com.capgemini.serviciosya.beans.domain;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Provider.java
//  @ Date : 11/09/2018
//  @ Author : 
//
//




public class Provider extends Person {	
	
	private Collection<Skill> skills;
	private Collection<Availability> availability;
	private float pricePerHour;
	
	public Provider() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	public Provider(int dni, String name, String lastName, String email, String phone, Date birthDate,
			Address address) {
		super(dni, name, lastName, email, phone, birthDate, address);
		// TODO Auto-generated constructor stub
	}

	public Collection<Skill> getSkills() {
		return skills;
	}
	
	public float calculateFinalPrice(LocalDateTime hoursOfWork) {
		return pricePerHour;
	
	}	
	public void setSkills(Collection<Skill> skills) {
		this.skills = skills;
	}
	public Collection<Availability> getAvailability() {
		return availability;
	}
	public void setAvailability(Collection<Availability> availability) {
		this.availability = availability;
	}
	public float getPricePerHour() {
		return pricePerHour;
	}
	public void setPricePerHour(float pricePerHour) {
		this.pricePerHour = pricePerHour;
	}
}
