package com.capgemini.serviciosya.beans.domain;

import java.time.LocalDateTime;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Service.java
//  @ Date : 11/09/2018
//  @ Author : 
//
//




public class Service {
	private Skill skill;
	private Provider provider;
	private Consumer consumer;
	private String expertise;
	private float payment;
	private LocalDateTime hoursOfWork;
	public Skill getSkill() {
		return skill;
	}
	public void setSkill(Skill skill) {
		this.skill = skill;
	}
	public Provider getProvider() {
		return provider;
	}
	public void setProvider(Provider provider) {
		this.provider = provider;
	}
	public Consumer getConsumer() {
		return consumer;
	}
	public void setConsumer(Consumer consumer) {
		this.consumer = consumer;
	}
	public String getExpertise() {
		return expertise;
	}
	public void setExpertise(String expertise) {
		this.expertise = expertise;
	}
	public float getPayment() {
		return payment;
	}
	public void setPayment(float payment) {
		this.payment = payment;
	}
	public LocalDateTime getHoursOfWork() {
		return hoursOfWork;
	}
	public void setHoursOfWork(LocalDateTime hoursOfWork) {
		this.hoursOfWork = hoursOfWork;
	}
}
