package com.capgemini.serviciosya.beans.domain;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Skill.java
//  @ Date : 11/09/2018
//  @ Author : 
//
//




public class Skill {
	private String skill;
	private String expertise;
	public Skill(String skill, String expertise) {
		super();
		this.skill = skill;
		this.expertise = expertise;
	}
	public String getSkill() {
		return skill;
	}
	public void setSkill(String skill) {
		this.skill = skill;
	}
	public String getExpertise() {
		return expertise;
	}
	public void setExpertise(String expertise) {
		this.expertise = expertise;
	}
}
